
const f =()=>{

           try {
    let a= 0
    //console.log(program)
    console.log("Program run succesfully")
    return
           } catch (error) {
    console.log("this is an error")
           }
           finally{
               console.log("i am a good girl")
               //close the file
               //exit the loop
               //write to the log file
               //usually we do final clean ups
           }
}
f()
console.log("end")